"""Migration integrity.

Runs against its own scratch database, because upgrading and downgrading
mutates the schema out from under anything else using it.
"""
from __future__ import annotations

import os
from collections.abc import Iterator

import psycopg
import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy.engine import make_url

from config import settings

pytestmark = pytest.mark.postgres

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_SCRATCH_DB = "baseball_migrations_test"


def _dsn(url_str: str, database: str) -> str:
    url = make_url(url_str).set(database=database)
    return url.render_as_string(hide_password=False).replace(
        "postgresql+psycopg://", "postgresql://"
    )


@pytest.fixture
def scratch_url() -> Iterator[str]:
    base = settings.test_database_url
    admin = _dsn(base, "postgres")

    try:
        with psycopg.connect(admin, autocommit=True) as conn:
            conn.execute("SELECT 1")
    except psycopg.OperationalError:
        pytest.skip("Postgres unavailable; docker compose up -d postgres")

    with psycopg.connect(admin, autocommit=True) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{_SCRATCH_DB}" WITH (FORCE)')
        conn.execute(f'CREATE DATABASE "{_SCRATCH_DB}"')

    yield make_url(base).set(database=_SCRATCH_DB).render_as_string(
        hide_password=False
    )

    with psycopg.connect(admin, autocommit=True) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{_SCRATCH_DB}" WITH (FORCE)')


@pytest.fixture
def alembic_config(scratch_url: str) -> Iterator[Config]:
    cfg = Config(os.path.join(_PROJECT_ROOT, "alembic.ini"))
    previous = os.environ.get("ALEMBIC_DATABASE_URL")
    os.environ["ALEMBIC_DATABASE_URL"] = scratch_url
    try:
        yield cfg
    finally:
        if previous is None:
            os.environ.pop("ALEMBIC_DATABASE_URL", None)
        else:
            os.environ["ALEMBIC_DATABASE_URL"] = previous


def _tables(url: str) -> set[str]:
    with psycopg.connect(
        _dsn(url, make_url(url).database), autocommit=True
    ) as conn:
        return {
            r[0]
            for r in conn.execute(
                "SELECT tablename FROM pg_tables WHERE schemaname = 'public'"
            ).fetchall()
        }


class TestMigrationRoundTrip:
    def test_upgrade_creates_the_schema(self, alembic_config, scratch_url):
        command.upgrade(alembic_config, "head")
        assert {"bets", "odds_snapshots", "ingest_runs"} <= _tables(scratch_url)

    def test_downgrade_removes_everything(self, alembic_config, scratch_url):
        command.upgrade(alembic_config, "head")
        command.downgrade(alembic_config, "base")

        remaining = _tables(scratch_url)
        # alembic_version survives a downgrade to base by design; nothing
        # of ours should.
        assert remaining <= {"alembic_version"}

    def test_full_round_trip(self, alembic_config, scratch_url):
        # Catches a broken downgrade() on day one rather than in six months,
        # when it is needed under pressure.
        command.upgrade(alembic_config, "head")
        command.downgrade(alembic_config, "base")
        command.upgrade(alembic_config, "head")

        assert {"bets", "odds_snapshots", "ingest_runs"} <= _tables(scratch_url)


class TestModelMigrationParity:
    def test_models_match_migrations(self, alembic_config):
        """The highest-value test in this file.

        Autogenerate against a migrated database must produce an empty diff.
        Without it, a column added to a model but not to a migration works
        perfectly in any test that builds its schema from metadata, and
        fails only on a real deployment.
        """
        command.upgrade(alembic_config, "head")
        try:
            command.check(alembic_config)
        except AutogenerateDiffsDetected as exc:
            pytest.fail(
                "Models have drifted from migrations. Run "
                "`alembic revision --autogenerate` and review the result.\n"
                f"{exc}"
            )


class TestConstraintsSurviveMigration:
    def test_check_constraints_are_created_by_the_migration(
        self, alembic_config, scratch_url
    ):
        # The constraints are the schema's actual guarantees, so they have
        # to come from the migration - not merely from the model metadata
        # that tests happen to use.
        command.upgrade(alembic_config, "head")

        with psycopg.connect(
            _dsn(scratch_url, _SCRATCH_DB), autocommit=True
        ) as conn:
            names = {
                r[0]
                for r in conn.execute(
                    "SELECT conname FROM pg_constraint WHERE contype = 'c'"
                ).fetchall()
            }

        assert {
            "ck_odds_snapshots_odds_american_valid",
            "ck_odds_snapshots_line_presence",
            "ck_odds_snapshots_selection_matches_market",
            "ck_bets_odds_american_valid",
            "ck_bets_settlement_coherent",
            "ck_bets_stake_positive",
            "ck_ingest_runs_finished_iff_done",
        } <= names

    def test_migration_does_not_import_application_code(self):
        # A migration is a historical record that must keep running years
        # later. If it imported database.utc, renaming or deleting that
        # module would break already-applied history.
        versions = os.path.join(
            _PROJECT_ROOT, "database", "migrations", "versions"
        )
        for name in os.listdir(versions):
            if not name.endswith(".py"):
                continue
            with open(os.path.join(versions, name), encoding="utf-8") as fh:
                source = fh.read()
            assert "database.utc" not in source, name
            assert "from database" not in source, name
            assert "import database" not in source, name
