"""Migration integrity.

Runs against its own scratch database, because upgrading and downgrading
mutates the schema out from under anything else using it.
"""

from __future__ import annotations

import os
from collections.abc import Iterator
from types import SimpleNamespace

import psycopg
import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy.engine import make_url

from config import settings

pytestmark = pytest.mark.postgres

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_SCRATCH_DB = "baseball_migrations_test"


def _dsn(url_str: str, database: str) -> str:
    url = make_url(url_str).set(database=database)
    return url.render_as_string(hide_password=False).replace(
        "postgresql+psycopg://", "postgresql://"
    )


@pytest.fixture
def scratch_url() -> Iterator[str]:
    base = settings.test_database_url
    admin = _dsn(base, "postgres")

    try:
        with psycopg.connect(admin, autocommit=True) as conn:
            conn.execute("SELECT 1")
    except psycopg.OperationalError:
        pytest.skip("Postgres unavailable; docker compose up -d postgres")

    with psycopg.connect(admin, autocommit=True) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{_SCRATCH_DB}" WITH (FORCE)')
        conn.execute(f'CREATE DATABASE "{_SCRATCH_DB}"')

    yield make_url(base).set(database=_SCRATCH_DB).render_as_string(hide_password=False)

    with psycopg.connect(admin, autocommit=True) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{_SCRATCH_DB}" WITH (FORCE)')


@pytest.fixture
def alembic_config(scratch_url: str) -> Iterator[Config]:
    cfg = Config(os.path.join(_PROJECT_ROOT, "alembic.ini"))
    previous = os.environ.get("ALEMBIC_DATABASE_URL")
    os.environ["ALEMBIC_DATABASE_URL"] = scratch_url
    try:
        yield cfg
    finally:
        if previous is None:
            os.environ.pop("ALEMBIC_DATABASE_URL", None)
        else:
            os.environ["ALEMBIC_DATABASE_URL"] = previous


def _tables(url: str) -> set[str]:
    with psycopg.connect(_dsn(url, make_url(url).database), autocommit=True) as conn:
        return {
            r[0]
            for r in conn.execute(
                "SELECT tablename FROM pg_tables WHERE schemaname = 'public'"
            ).fetchall()
        }


class TestMigrationRoundTrip:
    def test_upgrade_creates_the_schema(self, alembic_config, scratch_url):
        command.upgrade(alembic_config, "head")
        assert {"bets", "odds_snapshots", "ingest_runs"} <= _tables(scratch_url)

    def test_downgrade_removes_everything(self, alembic_config, scratch_url):
        command.upgrade(alembic_config, "head")
        command.downgrade(alembic_config, "base")

        remaining = _tables(scratch_url)
        # alembic_version survives a downgrade to base by design; nothing
        # of ours should.
        assert remaining <= {"alembic_version"}

    def test_full_round_trip(self, alembic_config, scratch_url):
        # Catches a broken downgrade() on day one rather than in six months,
        # when it is needed under pressure.
        command.upgrade(alembic_config, "head")
        command.downgrade(alembic_config, "base")
        command.upgrade(alembic_config, "head")

        assert {"bets", "odds_snapshots", "ingest_runs"} <= _tables(scratch_url)


class TestOwnershipGuard:
    """env.py must refuse to migrate a database this project does not own.

    The scenario this exists for is real: a native PostgreSQL install on the
    development machine listens on 5432 and holds the v1 project's live
    data, while this project's Postgres is on 5433. One character in a URL
    separates "migrate my scratch database" from "add three tables to a live
    system and then drop them on the next downgrade".
    """

    def test_refuses_a_database_containing_foreign_tables(
        self, alembic_config, scratch_url
    ):
        with psycopg.connect(_dsn(scratch_url, _SCRATCH_DB), autocommit=True) as conn:
            conn.execute("CREATE TABLE games (id int primary key)")
            conn.execute("CREATE TABLE model_registry (id int primary key)")

        with pytest.raises(SystemExit) as exc:
            command.upgrade(alembic_config, "head")

        message = str(exc.value)
        assert "REFUSING TO MIGRATE" in message
        assert "games" in message
        assert "model_registry" in message
        # And it must not have partially applied anything.
        assert not ({"bets", "odds_snapshots"} & _tables(scratch_url))

    def test_allows_an_empty_database(self, alembic_config, scratch_url):
        # A virgin database is the normal case for a first migration.
        command.upgrade(alembic_config, "head")
        assert {"bets", "odds_snapshots", "ingest_runs"} <= _tables(scratch_url)

    def test_allows_a_database_holding_only_our_tables(
        self, alembic_config, scratch_url
    ):
        command.upgrade(alembic_config, "head")
        command.downgrade(alembic_config, "base")
        command.upgrade(alembic_config, "head")
        assert {"bets", "odds_snapshots", "ingest_runs"} <= _tables(scratch_url)

    def test_the_guard_does_not_swallow_the_migration_transaction(
        self, alembic_config, scratch_url
    ):
        """Regression: the check must not run on the migration connection.

        Any query on that connection before context.begin_transaction()
        implicitly opens a transaction. Alembic then sees one active,
        returns a no-op context manager instead of its own, and never
        commits - so the migration logs "Running upgrade -> 0001", creates
        nothing, and rolls back silently on close. This asserts the tables
        genuinely exist afterwards rather than trusting the log line.
        """
        command.upgrade(alembic_config, "head")

        with psycopg.connect(_dsn(scratch_url, _SCRATCH_DB), autocommit=True) as conn:
            version = conn.execute("SELECT version_num FROM alembic_version").fetchone()
            columns = conn.execute(
                "SELECT count(*) FROM information_schema.columns "
                "WHERE table_name = 'odds_snapshots'"
            ).fetchone()

        # The version table and the actual schema must agree.
        assert version is not None
        assert version[0] == "0001"
        assert columns is not None
        assert columns[0] > 0


class TestDataLossGuard:
    """A downgrade must not silently destroy observed prices.

    The ownership guard protects against migrating somebody else's database.
    From Phase 1 the catastrophic path is `alembic downgrade base` against
    OUR OWN database holding a week of odds_snapshots - which the ownership
    guard waves through, correctly, because those tables are ours.

    Observed prices are the only thing here that cannot be re-fetched: a
    game can be re-ingested and a model retrained, but the price a book
    showed at a particular instant is gone once dropped.
    """

    def _seed_one_snapshot(self, scratch_url: str) -> None:
        with psycopg.connect(_dsn(scratch_url, _SCRATCH_DB), autocommit=True) as conn:
            conn.execute(
                "INSERT INTO ingest_runs (source, run_kind, status, started_at,"
                " finished_at) VALUES ('t','t','success', now(), now())"
            )
            conn.execute(
                "INSERT INTO odds_snapshots (ingest_run_id, game_pk, game_date,"
                " commence_time_utc, book, market, selection, line,"
                " odds_american, captured_at) VALUES"
                " (1, 776543, DATE '2026-07-27', now(), 'pinnacle',"
                " 'moneyline', 'away', NULL, 130, now())"
            )

    def test_refuses_to_downgrade_a_populated_database(
        self, alembic_config, scratch_url
    ):
        command.upgrade(alembic_config, "head")
        self._seed_one_snapshot(scratch_url)

        with pytest.raises(SystemExit) as exc:
            command.downgrade(alembic_config, "base")

        message = str(exc.value)
        assert "REFUSING TO DOWNGRADE" in message
        assert "1 observed price" in message
        assert "allow_data_loss=1" in message
        # Nothing was dropped.
        assert {"bets", "odds_snapshots", "ingest_runs"} <= _tables(scratch_url)

    def test_allows_a_downgrade_of_an_empty_database(self, alembic_config, scratch_url):
        # No prices means nothing irreplaceable to lose.
        command.upgrade(alembic_config, "head")
        command.downgrade(alembic_config, "base")
        assert _tables(scratch_url) <= {"alembic_version"}

    def test_the_override_flag_permits_it(self, alembic_config, scratch_url):
        command.upgrade(alembic_config, "head")
        self._seed_one_snapshot(scratch_url)

        alembic_config.cmd_opts = SimpleNamespace(x=["allow_data_loss=1"])
        command.downgrade(alembic_config, "base")
        assert _tables(scratch_url) <= {"alembic_version"}

    def test_upgrades_are_never_blocked_by_it(self, alembic_config, scratch_url):
        # The guard is about direction, not about the table being populated.
        command.upgrade(alembic_config, "head")
        self._seed_one_snapshot(scratch_url)
        command.upgrade(alembic_config, "head")  # no-op, must not raise


class TestModelMigrationParity:
    def test_models_match_migrations(self, alembic_config):
        """The highest-value test in this file.

        Autogenerate against a migrated database must produce an empty diff.
        Without it, a column added to a model but not to a migration works
        perfectly in any test that builds its schema from metadata, and
        fails only on a real deployment.
        """
        command.upgrade(alembic_config, "head")
        try:
            command.check(alembic_config)
        except AutogenerateDiffsDetected as exc:
            pytest.fail(
                "Models have drifted from migrations. Run "
                "`alembic revision --autogenerate` and review the result.\n"
                f"{exc}"
            )


class TestConstraintsSurviveMigration:
    def test_check_constraints_are_created_by_the_migration(
        self, alembic_config, scratch_url
    ):
        # The constraints are the schema's actual guarantees, so they have
        # to come from the migration - not merely from the model metadata
        # that tests happen to use.
        command.upgrade(alembic_config, "head")

        with psycopg.connect(_dsn(scratch_url, _SCRATCH_DB), autocommit=True) as conn:
            names = {
                r[0]
                for r in conn.execute(
                    "SELECT conname FROM pg_constraint WHERE contype = 'c'"
                ).fetchall()
            }

        assert {
            "ck_odds_snapshots_odds_american_valid",
            "ck_odds_snapshots_line_presence",
            "ck_odds_snapshots_selection_matches_market",
            "ck_bets_odds_american_valid",
            "ck_bets_settlement_coherent",
            "ck_bets_stake_positive",
            "ck_ingest_runs_finished_iff_done",
        } <= names

    def test_migration_does_not_import_application_code(self):
        # A migration is a historical record that must keep running years
        # later. If it imported database.utc, renaming or deleting that
        # module would break already-applied history.
        versions = os.path.join(_PROJECT_ROOT, "database", "migrations", "versions")
        for name in os.listdir(versions):
            if not name.endswith(".py"):
                continue
            with open(os.path.join(versions, name), encoding="utf-8") as fh:
                source = fh.read()
            assert "database.utc" not in source, name
            assert "from database" not in source, name
            assert "import database" not in source, name
