"""bets odds_snapshots ingest_runs

Phase 0 schema: persistence for the CLV measurement loop.

Three things here are load-bearing and easy to undo by accident:

1. `odds_snapshots` is APPEND-ONLY: no UPDATE, ever. But the same
   observation written twice is not two observations, so the natural key
   (game_pk, market, selection, book, line, captured_at) is UNIQUE and
   writers use ON CONFLICT DO NOTHING - which inserts or does not, and
   never rewrites a row. A retried ingest run is therefore idempotent
   instead of pushing de-duplication onto every read forever.

   NULLS NOT DISTINCT is essential, not decoration. Postgres treats NULLs
   as distinct in a unique index by default, so without it every moneyline
   row - where line IS NULL, the most common market - would collide with
   nothing and duplicate freely. Requires Postgres 15+; we target 16.

   This only works because `captured_at` is stamped from the owning ingest
   run's started_at rather than now(). A retry writing a fresh now() would
   land microseconds from the original, collide with nothing, and be stored
   as a second observation of one real observation.

2. `game_date` (DATE, venue-local) and `commence_time_utc` (TIMESTAMPTZ)
   hold different facts and neither is derivable from the other. A 10:10pm
   Pacific game is 05:10 UTC the NEXT day, so computing game_date as
   commence_time_utc::date drops late West Coast games from any query keyed
   on the slate date.

3. The point-in-time lookup is served by TWO PARTIAL indexes split on
   line-presence, not one index. Do not consolidate them.

     ix_odds_snapshots_pit_no_line
       (game_pk, market, selection, book, captured_at, id) WHERE line IS NULL
     ix_odds_snapshots_pit_lined
       (game_pk, market, selection, book, line, captured_at, id)
                                                  WHERE line IS NOT NULL

   A btree yields ordered output on a trailing column only when every
   preceding column is bound by EQUALITY. `line IS NULL` is a NullTest, not
   an equality operator, so it never forms an equivalence class with a
   constant and the planner cannot drop the `line` pathkey - it reads every
   matching row and sorts. At 400k rows a single index containing `line`
   cost 289.99 against 8.47 for the ordered plan.

   Dropping `line` entirely fixes the ordering but makes a lined lookup scan
   every snapshot for that game/market/selection/book across ALL lines and
   filter. Splitting gets both: the unlined index absorbs `line IS NULL`
   into its predicate so it is not a column at all, and the lined index has
   `line = $5` as a genuine equality that narrows the scan.

   This depends on the query emitting `line IS NULL` or `line = $5` so the
   planner can match a predicate. `IS NOT DISTINCT FROM` matches neither and
   is not indexable at all. See betting/clv.py::find_closing_snapshot.

There is intentionally no `games` table yet, so `game_pk` carries no foreign
key - it is a bare indexed integer until a schedule ingest exists to own it.


Revision ID: 0001
Revises: 
Create Date: 2026-07-27 16:02:16.917858
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('commence_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('book', sa.Text(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('selection', sa.Text(), nullable=False),
    sa.Column('line', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('odds_american', sa.Integer(), nullable=False),
    sa.Column('stake_cents', sa.BigInteger(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout_cents', sa.BigInteger(), nullable=True),
    sa.Column('model_prob', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(market = 'moneyline' AND line IS NULL) OR (market <> 'moneyline' AND line IS NOT NULL)", name=op.f('ck_bets_line_presence')),
    sa.CheckConstraint("(market = 'total' AND selection IN ('over','under')) OR (market <> 'total' AND selection IN ('home','away'))", name=op.f('ck_bets_selection_matches_market')),
    sa.CheckConstraint("(status = 'open' AND settled_at IS NULL AND payout_cents IS NULL) OR (status <> 'open' AND settled_at IS NOT NULL AND payout_cents IS NOT NULL)", name=op.f('ck_bets_settlement_coherent')),
    sa.CheckConstraint("market IN ('moneyline','total','run_line')", name=op.f('ck_bets_market')),
    sa.CheckConstraint("selection IN ('home','away','over','under')", name=op.f('ck_bets_selection')),
    sa.CheckConstraint("status IN ('open','won','lost','push','void')", name=op.f('ck_bets_status')),
    sa.CheckConstraint('game_pk > 0', name=op.f('ck_bets_game_pk_positive')),
    sa.CheckConstraint('model_prob IS NULL OR (model_prob > 0 AND model_prob < 1)', name=op.f('ck_bets_model_prob_range')),
    sa.CheckConstraint('odds_american <= -100 OR odds_american >= 100', name=op.f('ck_bets_odds_american_valid')),
    sa.CheckConstraint('payout_cents IS NULL OR payout_cents >= 0', name=op.f('ck_bets_payout_nonneg')),
    sa.CheckConstraint('stake_cents > 0', name=op.f('ck_bets_stake_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bets'))
    )
    op.create_index('ix_bets_game_date', 'bets', ['game_date'], unique=False)
    op.create_index('ix_bets_game_pk', 'bets', ['game_pk'], unique=False)
    op.create_index('ix_bets_open', 'bets', ['placed_at'], unique=False, postgresql_where=sa.text("status = 'open'"))
    op.create_table('ingest_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('run_kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_written', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('api_requests', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("(status = 'running') = (finished_at IS NULL)", name=op.f('ck_ingest_runs_finished_iff_done')),
    sa.CheckConstraint("status <> 'failed' OR error IS NOT NULL", name=op.f('ck_ingest_runs_failed_has_error')),
    sa.CheckConstraint("status IN ('running','success','partial','failed')", name=op.f('ck_ingest_runs_status')),
    sa.CheckConstraint('rows_written >= 0 AND api_requests >= 0', name=op.f('ck_ingest_runs_counts_nonneg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_runs'))
    )
    op.create_index('ix_ingest_runs_running', 'ingest_runs', ['started_at'], unique=False, postgresql_where=sa.text("status = 'running'"))
    op.create_index('ix_ingest_runs_source_started', 'ingest_runs', ['source', 'started_at'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('commence_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('book', sa.Text(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('selection', sa.Text(), nullable=False),
    sa.Column('line', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('odds_american', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(market = 'moneyline' AND line IS NULL) OR (market <> 'moneyline' AND line IS NOT NULL)", name=op.f('ck_odds_snapshots_line_presence')),
    sa.CheckConstraint("(market = 'total' AND selection IN ('over','under')) OR (market <> 'total' AND selection IN ('home','away'))", name=op.f('ck_odds_snapshots_selection_matches_market')),
    sa.CheckConstraint("market IN ('moneyline','total','run_line')", name=op.f('ck_odds_snapshots_market')),
    sa.CheckConstraint("selection IN ('home','away','over','under')", name=op.f('ck_odds_snapshots_selection')),
    sa.CheckConstraint('game_pk > 0', name=op.f('ck_odds_snapshots_game_pk_positive')),
    sa.CheckConstraint('odds_american <= -100 OR odds_american >= 100', name=op.f('ck_odds_snapshots_odds_american_valid')),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_runs.id'], name='fk_odds_snapshots_ingest_run'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odds_snapshots')),
    sa.UniqueConstraint('game_pk', 'market', 'selection', 'book', 'line', 'captured_at', name='uq_odds_snapshots_observation', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_odds_snapshots_game_captured', 'odds_snapshots', ['game_pk', 'captured_at'], unique=False)
    op.create_index('ix_odds_snapshots_ingest_run_id', 'odds_snapshots', ['ingest_run_id'], unique=False)
    op.create_index('ix_odds_snapshots_pit_lined', 'odds_snapshots', ['game_pk', 'market', 'selection', 'book', 'line', 'captured_at', 'id'], unique=False, postgresql_where=sa.text('line IS NOT NULL'))
    op.create_index('ix_odds_snapshots_pit_no_line', 'odds_snapshots', ['game_pk', 'market', 'selection', 'book', 'captured_at', 'id'], unique=False, postgresql_where=sa.text('line IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_odds_snapshots_pit_no_line', table_name='odds_snapshots', postgresql_where=sa.text('line IS NULL'))
    op.drop_index('ix_odds_snapshots_pit_lined', table_name='odds_snapshots', postgresql_where=sa.text('line IS NOT NULL'))
    op.drop_index('ix_odds_snapshots_ingest_run_id', table_name='odds_snapshots')
    op.drop_index('ix_odds_snapshots_game_captured', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index('ix_ingest_runs_source_started', table_name='ingest_runs')
    op.drop_index('ix_ingest_runs_running', table_name='ingest_runs', postgresql_where=sa.text("status = 'running'"))
    op.drop_table('ingest_runs')
    op.drop_index('ix_bets_open', table_name='bets', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('ix_bets_game_pk', table_name='bets')
    op.drop_index('ix_bets_game_date', table_name='bets')
    op.drop_table('bets')
    # ### end Alembic commands ###
