"""games table and foreign keys

Adds `games` and points odds_snapshots.game_pk / bets.game_pk at it.

ON DELETE RESTRICT, not CASCADE. Nothing should ever delete a game, and if
something tries it must fail loudly rather than quietly take the price
history with it. Observed prices cannot be re-fetched at any price.

game_pk is the primary key with no surrogate and no autoincrement: the value
comes from MLB. It is also STABLE ACROSS A POSTPONEMENT - StatsAPI reuses the
pk and moves the dates in place (pk 778431, postponed 2025-04-06, played
2025-08-09) - which is why there is no `rescheduled_as` column. A
permanently-NULL column would be a claim about the data that is not true.

The market-episode distinction survives without extra structure: that game
accumulates snapshots under one pk across two episodes, but each snapshot
stores game_date as reported at capture, so April rows say 2025-04-06 and
August rows say 2025-08-09. Separable with a GROUP BY. This is why the
denormalised game_date on odds_snapshots must not be "simplified" away later.

Two data steps run between the table and the constraints:

  1. Backfill odds_snapshots.game_date from games, so the FK lands on rows
     that agree with their game.
  2. Assert that no Pacific-venue snapshot has
     game_date = commence_time_utc::date. A 7pm Pacific first pitch is
     02:00 UTC the following day, so equality there means the date was
     derived from the UTC timestamp - the v1 defect this schema exists to
     prevent. Cheap check that it stayed dead.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_pk', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('commence_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('rescheduled_from_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('game_pk > 0', name=op.f('ck_games_game_pk_positive')),
    sa.PrimaryKeyConstraint('game_pk', name=op.f('pk_games'))
    )
    op.create_index('ix_games_commence_time_utc', 'games', ['commence_time_utc'], unique=False)
    op.create_index('ix_games_game_date', 'games', ['game_date'], unique=False)

    # --- data steps, between the table and the constraints -----------------

    # 1. Make odds_snapshots.game_date agree with its game. No-op on a fresh
    #    database; matters where snapshots predate `games`.
    op.execute(
        """
        UPDATE odds_snapshots s
           SET game_date = g.game_date
          FROM games g
         WHERE g.game_pk = s.game_pk
           AND s.game_date IS DISTINCT FROM g.game_date
        """
    )

    # 2. A Pacific venue's night game starts on the NEXT UTC date. A row
    #    where the two are equal had its game_date derived from the UTC
    #    timestamp, which is exactly the v1 bug. Fail the migration rather
    #    than carry it forward.
    bad = op.get_bind().execute(
        sa.text(
            """
            SELECT count(*) FROM odds_snapshots s
              JOIN games g ON g.game_pk = s.game_pk
             WHERE g.venue_id IN (1, 22, 680, 2395, 2529, 2680)
               AND s.game_date = (s.commence_time_utc AT TIME ZONE 'UTC')::date
               AND (s.commence_time_utc AT TIME ZONE 'UTC')::time < TIME '10:00'
            """
        )
    ).scalar_one()
    if bad:
        raise RuntimeError(
            f"{bad} odds_snapshots row(s) at a Pacific venue have "
            "game_date equal to their UTC date. A 7pm Pacific first pitch is "
            "02:00 UTC the NEXT day, so this means game_date was derived from "
            "commence_time_utc instead of taken from StatsAPI officialDate. "
            "Fix the ingest before migrating."
        )

    op.create_foreign_key('fk_bets_game', 'bets', 'games', ['game_pk'], ['game_pk'], ondelete='RESTRICT')
    op.create_foreign_key('fk_odds_snapshots_game', 'odds_snapshots', 'games', ['game_pk'], ['game_pk'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_odds_snapshots_game', 'odds_snapshots', type_='foreignkey')
    op.drop_constraint('fk_bets_game', 'bets', type_='foreignkey')
    op.drop_index('ix_games_game_date', table_name='games')
    op.drop_index('ix_games_commence_time_utc', table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
